# Generated by Django 5.0.3 on 2024-03-17 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=510, verbose_name='Caption')),
                ('description', models.TextField(blank=True, max_length=600, verbose_name='Description')),
                ('video', models.FileField(upload_to='moments', verbose_name='Video')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('archive', models.BooleanField(default=False)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moment',
                'verbose_name_plural': 'Moments',
            },
        ),
    ]
