# Generated by Django 5.0.7 on 2024-10-31 20:51

import django.db.models.deletion
import moments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.CharField(default=moments.models.create_custon_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('caption', models.CharField(blank=True, max_length=510, verbose_name='Caption')),
                ('description', models.TextField(blank=True, max_length=600, verbose_name='Description')),
                ('video', models.FileField(max_length=1000, upload_to='moments', verbose_name='Video')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('archive', models.BooleanField(default=False)),
                ('tags', models.TextField(blank=True, max_length=1000)),
                ('leaps', models.IntegerField(default=0)),
                ('cover_pic', models.ImageField(null=True, upload_to='moments_cover')),
                ('num_likes', models.IntegerField(default=0)),
                ('num_comments', models.IntegerField(default=0)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moment',
                'verbose_name_plural': 'Moments',
            },
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('timespan', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fruits', to=settings.AUTH_USER_MODEL)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='moments.moment')),
            ],
        ),
        migrations.CreateModel(
            name='Leaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timespan', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_leaps', to=settings.AUTH_USER_MODEL)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_leaps', to='moments.moment')),
            ],
            options={
                'indexes': [models.Index(fields=['moment'], name='moment_idx')],
            },
        ),
    ]
