# Generated by Django 5.0.3 on 2024-03-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='tags',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
