# Generated by Django 5.0.3 on 2024-03-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0002_moment_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='video',
            field=models.FileField(max_length=1000, upload_to='moments', verbose_name='Video'),
        ),
    ]
