# Generated by Django 5.0.3 on 2024-03-18 18:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0003_alter_moment_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
