# Generated by Django 5.0.3 on 2024-03-19 17:05

import moments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0005_alter_moment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='id',
            field=models.CharField(default=moments.models.create_custon_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
