# Generated by Django 5.0.3 on 2024-03-23 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0007_moment_leaps_leap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('timespan', models.DateTimeField(auto_now_add=True)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='moments.moment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fruits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
