# Generated by Django 5.0.3 on 2024-03-23 16:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0008_fruit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leap',
            new_name='Leaf',
        ),
    ]
