# Generated by Django 5.0.3 on 2024-03-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0009_rename_leap_leaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
