# Generated by Django 5.0.3 on 2024-05-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moments", "0010_alter_fruit_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="moment",
            name="cover_pic",
            field=models.ImageField(null=True, upload_to="moments_cover"),
        ),
    ]
