# Generated by Django 5.0.3 on 2024-03-14 06:00

import accounts.models
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN', unique=True, validators=[accounts.models.ValidationClass.validate_mobile], verbose_name='mobile number'),
        ),
    ]
