# Generated by Django 5.0.3 on 2024-04-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="num_blogs", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user", name="num_moments", field=models.IntegerField(default=0),
        ),
    ]
