# Generated by Django 5.0.3 on 2024-05-12 15:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_user_num_blogs_user_num_moments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                default=accounts.models.UserManager.default_profile_pic,
                null=True,
                upload_to="user_profiles",
            ),
        ),
    ]
