# Generated by Django 5.0.3 on 2024-06-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_user_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="num_posts", field=models.IntegerField(default=0),
        ),
    ]
