# Generated by Django 5.0.3 on 2024-03-28 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='user',
        ),
        migrations.CreateModel(
            name='StoryLodger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='storylodger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='story.storylodger'),
            preserve_default=False,
        ),
    ]
