# Generated by Django 5.0.3 on 2024-03-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_remove_story_user_storylodger_story_storylodger'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='caption',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
