# Generated by Django 5.0.3 on 2024-04-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_save'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='save',
            options={'verbose_name': 'Blog Saves'},
        ),
    ]
