# Generated by Django 5.0.3 on 2024-04-06 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
        ('features', '0003_alter_save_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='blog.blog'),
            preserve_default=False,
        ),
    ]
